### ISSUE TITLE
Docker startup from scratch

### ISSUE THREAD

**Issue by Starttoaster** [prabhatsharma/zinc#1]
The short of the problem is that I can't get Zinc in a container to stay running without pre-existing indexes to load. It seems that without an existing index in your `$DATA_PATH` directory, Zinc will panic and the docker container stops instantly before anyone would have the chance to have Zinc ingest any data.

I built an image from the Dockerfile in this repository using the command `docker build -t test .`;

I ran the following command: `docker run -d -v /server/zinc:/data -e DATA_PATH="/data" -e FIRST_ADMIN_USER=admin -e FIRST_ADMIN_PASSWORD=admin --name zinc test`

I observed that the container had stopped near-instantly, and so I ran `docker logs zinc` which returned the following:

```
{"level":"debug","time":"2021-12-03T20:09:04Z","message":"Loading indexes..."}
{"level":"debug","time":"2021-12-03T20:09:04Z","message":"Loading system indexes..."}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa299e4]

goroutine 1 [running]:
github.com/prabhatsharma/zinc/pkg/core.LoadZincSystemIndexes(0xc0003f6180, 0x0, 0x0)
        /go/src/github.com/prabhatsharma/zinc/pkg/core/LoadIndexes.go:26 +0x1a4
github.com/prabhatsharma/zinc/pkg/core.init()
        /go/src/github.com/prabhatsharma/zinc/pkg/core/types.go:10 +0x3e
```

It appears you need to do more to start Zinc without pre-existing data that your documentation does not mention.

**Comment by HeCorr** [comment]
@Starttoaster it seems that you need to [tweak the data dir permissions](https://github.com/prabhatsharma/zinc/issues/23#issuecomment-987641635)
