### ISSUE TITLE
Manual install steps?

### ISSUE THREAD

**Issue by jhfoo** [prabhatsharma/zinc#10]
I like to try installing on FreeBSD. How can I build from code?

**Comment by gedw99** [comment]
DO you know how to use a makefile ?

The repo does not have one, but i made one if you want it.

**Comment by jhfoo** [comment]
Just run `make `right?

**Comment by h3z** [comment]
check the file zinc/build.sh

install on macOS success:
```
cd web
npm install
npm run build

cd ..
go install github.com/rakyll/statik@latest
statik -src=./web/dist

CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-w -s" -o zinc
```

**Comment by jhfoo** [comment]
A few observations:
1. cypress failed for FreeBSD (Platform: "freebsd" is not supported). Can this be made optional since it's a testing library?
2. `go install github.com/rakyll/statik@latest` => downloads statik.go in statik/. I tried `go run ./statik/statik.go -src=./web/dist` and got this error: `package command-line-arguments is not a main package`

**Comment by prabhatsharma** [comment]
freebsd binaries are now available at https://github.com/prabhatsharma/zinc/releases

**Comment by jhfoo** [comment]
Very exciting! I was able to download and run zinc_0.1.1_freebsd_x86_64.tar.gz. Able to log into web ui without issues. Have not tested the REST API.

Notes:
1. Create data/ dir
2. Run with admin cred in environment per README.md

Thank you!

**Comment by gedw99** [comment]
@jhfoo great 

@prabhatsharma if you want a make file ( that i use ) PR'ed justholler. 
makes things easier people to try sometimes

**Comment by prabhatsharma** [comment]
@gedw99 That will be awesome if you can make a PR for the makefile.
