### ISSUE TITLE
Since you claim Zinc is a Drop-In replacement will you be aiming for a full API replica at any point?

### ISSUE THREAD

**Issue by Leopere** [prabhatsharma/zinc#103]
It would make for a beautiful replacement for ElasticSearch to be able to do away with the dependency on ES entirely with an Actual drop-in replacement not just one for data ingress.  The fact that this exists gives me hope but ES seems like it should definitely be replaced at some point.  It's a pain in the butt.

**Comment by prabhatsharma** [comment]
We already support search DSL as well which covers both read and write aspects. A major part has already been implemented. check /es endpoints. Does it help your use case?
