### ISSUE TITLE
Starting this on windows not working

### ISSUE THREAD

**Issue by T100D** [prabhatsharma/zinc#15]
Tried several options, but cat get it to go up and running from a command schell

$ FIRST_ADMIN_USER=admin FIRST_ADMIN_PASSWORD=Complexpass 123 zinc.exe
'FIRST_ADMIN_USER' is not recognized as an internal or external command,
operable program or batch file.

other try:

zinc.exe FIRST_ADMIN_USER=admin FIRST_ADMIN_PASSWORD=QNHadmin
{"level":"debug","time":"2021-12-06T16:19:12+01:00","message":"Loading indexes..."}
{"level":"debug","time":"2021-12-06T16:19:12+01:00","message":"Loading system indexes..."}
{"level":"debug","time":"2021-12-06T16:19:12+01:00","message":"Index loaded: _users"}
{"level":"debug","time":"2021-12-06T16:19:12+01:00","message":"Index loaded: _index_mapping"}
2021/12/06 16:19:12 FIRST_ADMIN_USER and FIRST_ADMIN_PASSWORD must be set on first start. You should also change the credentials after first login.

**Comment by B0bbyD0llar** [comment]
you can create an .env file with this content (replace with your credentials):

```
FIRST_ADMIN_USER=admin
FIRST_ADMIN_PASSWORD=password
```

or you can create env vars from PowerShell directly with:
```powershell
$env:FIRST_ADMIN_USER="admin"
$env:FIRST_ADMIN_PASSWORD="password"
```

This works for me. Maybe this could also be mentioned in the README.

**Comment by T100D** [comment]
> you can create an .env file with this content (replace with your credentials):
> 
> ```
> FIRST_ADMIN_USER=admin
> FIRST_ADMIN_PASSWORD=password
> ```
> 

Tank you @B0bbyD0llar. The .env file getst is going, now I have tot doe something on the local network apperently.

```
[GIN-debug] Listening and serving HTTP on :4080
[GIN-debug] [ERROR] listen tcp :4080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```

**Comment by T100D** [comment]
@B0bbyD0llar there was nothing on it

solved after using 

net stop winnat
net start winnat

We are on the go,, thank you

**Comment by HeCorr** [comment]
@T100D please close the issue if it has been solved  :)

**Comment by T100D** [comment]
Solved after uscin a .env file
