### ISSUE TITLE
Request: Cursor pagination

### ISSUE THREAD

**Issue by arunbabucode** [prabhatsharma/zinc#19]
Would be great to have a cursor pagination for the search results.

**Comment by luigidid** [comment]
Hello, in the meantime, thank you for the constantly evolving product. Very useful for my projects. One question though: from version 0.1.3 onwards, I don't understand how to enable the limitation of 20 "records" on the "ZincSearch" web application. Thank you. I only ever see 20 records.

**Comment by safeie** [comment]
check, i will add the future.

**Comment by prabhatsharma** [comment]
Is this for UI or API? It has been implemented in the API already using the PR https://github.com/prabhatsharma/zinc/pull/56 .

For UI the default search when an index is selected returns 20 records which serves as showing a sample of the data. When you search for a specific term you can get a maximum of 1000 records which are paginated on the UI.

@arunbabucode  @luigidid Do you need something more than any of what I mentioned.

**Comment by prabhatsharma** [comment]
@safeie Did you have something else in mind on how you wanted it to look like?

**Comment by safeie** [comment]
@prabhatsharma it looks a UI bug, `pagination.RowsNumber` is not be set when search result. so, the ui not know the total, as result, ui not show pagination.

**Comment by safeie** [comment]
@prabhatsharma i saw you set max_results: 100, so it can only got 100 items, i think can use ui request with pagenation, response rowsPerPage per request, when click the next page button, request next page data from server.

**Comment by luigidid** [comment]
Hi, yes indeed, as I wrote in the other thread, with the search by filter: * it returns me at most 100 records (not 1000 records, as happened with the previous version).

I believe that having a limitation in the presentation of the results in the web interface, limits their use and leads to build a personal UI using data extraction using the rest calls with the use of the paging filter, example:

{
     "search_type": "querystring",
     "query":
     {
         "term": "*"
     },
     **"from": 1,**
     **"max_results": 100000,**
     "fields": ["_all"]
}

Is it possible to get a modification that implements this? Thanks in advance.

**Comment by prabhatsharma** [comment]
I forgot that I changed 1000 to 100 records limit. My thought process in limiting the number of records returned was that in general you do not look for 5 pages of results. You filter by queries to find exact records. 

Also more records means more to download in a single call. Current pagination in the UI happens on the client side and not on server side.

A better implementation would be to allow the user to provide the number of max records to return in the UI.

**Comment by arunbabucode** [comment]
Was looking for the API implementation and the linked issue covers it. Closing this since I find what was looking for.

**Comment by luigidid** [comment]
@prabhatsharma, I'm sorry but I don't know what you say. If I were to search and the resultset is just over 100 records, my search would still be limited to 100. What good would it do? At least for my use of it, I am entering approximately 7,000 - 8,000 records daily. As a solution I would propose to be able to set the values of maxresults and more, in a special properties file or environment variables. Thank you

**Comment by prabhatsharma** [comment]
@luigidid Let's discuss it in https://github.com/prabhatsharma/zinc/issues/62
