### ISSUE TITLE
"404 page not found" trying to post data on Windows

### ISSUE THREAD

**Issue by helgeklein** [prabhatsharma/zinc#31]
Whenever I try to post data I get the message "404 page not found". This is with version 0.1.1 on Windows 10. I can access the web UI without problems.

This is what I did:

1. Downloaded Zinc 0.1.1.
2. In a command prompt, cd'd to the directory where I unpacked `zinc.exe`
3. Set an admin user environment variable: `set FIRST_ADMIN_USER=admin`
4. Set an admin password environment variable: `set FIRST_ADMIN_PASSWORD=Pass123`
5. Created a `data` subdirectory
5. Started `zinc.exe`
6. Opened the web UI in my browser successfully at `http://localhost:4080/ui/`

I _unsuccessfully_ tried to post data to the following URLs:

1. http://localhost:4080/api/_bulk
2. http://localhost:4080/api/myindexname/_bulk
3. http://localhost:4080/api/myindexname/document

Am I missing something?

**Comment by susinths** [comment]
You'd need to POST to /es/_bulk

**Comment by helgeklein** [comment]
It would be nice if it was possible to specify the index and type via the URL, similarly to what is possible with Elasticsearch.

Example: `http://localhost:4080/es/indexname/typename/_bulk`

Do you have any plans for that?

**Comment by prabhatsharma** [comment]
@helgeklein You can specify the indexname in the URL, but there are no types of indexes yet in zinc. It's too early in the project to build any plans and say yes or no. I would prefer to let the community drive the feature requests. Can you please create a separate issue for this. Based on how the community responds the specific feature we can prioritize it.
