### ISSUE TITLE
Questions about search results

### ISSUE THREAD

**Issue by AlanCZ** [prabhatsharma/zinc#34]
I save the data into zinc through a python script, and when I search for a complete word, the result is correct. But when searching for a part of the word, no results were found. Is this problematic?

**Comment by hugollanos** [comment]
Do you have tried with a wildcard (like *)?

**Comment by prabhatsharma** [comment]
You should be able to do wildcard search. e.g. to search for london you could do lond*

**Comment by helmut72** [comment]
Also the chars in the search field must be all lowercase, regardless if the finding is in uppercase. But the founded chars or word won't be highlighted. I've tested with the "Olympics" example.
