### ISSUE TITLE
Chatgroup for zinc? (EG, discord)

### ISSUE THREAD

**Issue by kingdevnl** [prabhatsharma/zinc#40]
It would be nice if there could be a discord server for zinc,
Plenty of OSS projects got a chat group somewhere.

**Comment by prabhatsharma** [comment]
Totally agree. You folks are awesome.

Here is the link to join. I will be updating the readme. I have also been working on documentation and website.

https://join.slack.com/t/newworkspace-osi2817/shared_invite/zt-10a4jb2nl-tQUWwVQgylFEImicA7Fw6A
