### ISSUE TITLE
 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ak476565** [prabhatsharma/zinc#43]
![微信截图_20211213192001](https://user-images.githubusercontent.com/3871722/145803518-5a1b6619-fe44-4900-bffe-ba9a12419607.png)

**Comment by ak476565** [comment]
I built the image on Ubuntu using the dockerfile that comes with the project  

Linux ubuntu2004 5.4.0-86-generic #97-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

**Comment by wangyufengGoGoGo** [comment]
Encountered the same problem

**Comment by prabhatsharma** [comment]
Possible duplicate and the solution being https://github.com/prabhatsharma/zinc/issues/23#issuecomment-987641635 . Let me know if it works.

**Comment by prabhatsharma** [comment]
@ak476565 @wangyufengGoGoGo Do you still have challenges?
