### ISSUE TITLE
Homebrew integration

### ISSUE THREAD

**Issue by bbkane** [prabhatsharma/zinc#46]
Hello, zinc uses GoReleaser, which offers excellent [Homebrew integration](https://goreleaser.com/customization/homebrew/). Would you be open to adding this integration? Here's [what I do](https://github.com/bbkane/starghaze/blob/8cdaf042b855ccada63e9d8b3aaec104491e57c0/.goreleaser.yml#L30) for reference

**Comment by prabhatsharma** [comment]
Yeah, definitely, I intend to add homebrew as an installation mechanism as it will make life easier for folks trying to install zinc. I am wrapping up a couple of things and will get to it as soon as I can.
