### ISSUE TITLE
README bulk ingestions example data 404s

### ISSUE THREAD

**Issue by bbkane** [prabhatsharma/zinc#50]
`curl`ing (or simply clicking in a browser) https://github.com/prabhatsharma/zinc/releases/download/v0.1.1/https://github.com/prabhatsharma/zinc/releases/download/v0.1.1/olympics.ndjson.gz  returns a `404 Not Found` error

**Comment by prabhatsharma** [comment]
Here is the right stuff - 

> curl -L https://github.com/prabhatsharma/zinc/releases/download/v0.1.1/olympics.ndjson.gz -o olympics.ndjson.gz

I will fix the README

**Comment by bbkane** [comment]
Thank you!!
