### ISSUE TITLE
Compatibility with elasticsearch APIs

### ISSUE THREAD

**Issue by iFrozenPhoenix** [prabhatsharma/zinc#52]
First of all, this is a really cool project, with really impressive response times in searches.

According to the docs there are currently a thew ES APIs implemented.
I'd like to ask if compatibility, I mean in regards of a drop-in replacement for workloads where ES is the backend, is intended?

Are there already experiences with deployments where ES is normally used as a backend like Jaeger, OpenCTI or other projects?

**Comment by prabhatsharma** [comment]
Zinc is still in alpha. It currently provides compatibility only with log ingestion APIs (individual records and bulk)

**Comment by iFrozenPhoenix** [comment]
@prabhatsharma ok I have understood that, but what is the target?
Is it the target to be compatible or is it the target to be a standalone product that is similar to ES?

**Comment by prabhatsharma** [comment]
Target is to build a system that allows users to analyze their logs well, which does not necessarily mean ES compatibility. Ingestion APIs were easy to make compatible and made a lot of sense as ingestion using fluentnbit/fluentd/vector and anything else required no additional effort once this is done. However rebuilding ES APIs and its DSL would be a lot more work and I think that effort will be well spent doing other things.

**Comment by thomas-mc-work** [comment]
too bad :disappointed:
