### ISSUE TITLE
Search over all time

### ISSUE THREAD

**Issue by terrysklirosFS** [prabhatsharma/zinc#54]
It would be great if there was an option in the time settings for a search which would let you set the search time frame to all time.

**Comment by prabhatsharma** [comment]
What is the use case for this? What kind of data are you indexing?

**Comment by terrysklirosFS** [comment]
I have static datasets where the timestamp is irrelevant. Every query that I make should be on all the available data.

**Comment by prabhatsharma** [comment]
Are you querying using the UI or API? In the API you can simply omit the
start and end fields.

**Comment by terrysklirosFS** [comment]
I'm using the UI. Would it be possible to omit these fields from the UI as well?

**Comment by prabhatsharma** [comment]
I will leave this issue open and depending on the feedback from the community, if more folks ask for this I will prioritize this. For now, you can use larger periods or use absolute time periods of longer duration.

**Comment by gvesna** [comment]
I'm missing this option too...

**Comment by safeie** [comment]
it's already add full time search in UI #72

**Comment by prabhatsharma** [comment]
Released in https://github.com/prabhatsharma/zinc/releases/tag/v0.1.5
