### ISSUE TITLE
Feature request:  "DELETE" option to the Zinc API

### ISSUE THREAD

**Issue by beave** [prabhatsharma/zinc#55]
Adding the "DELETE" option to the Zinc API would allow users to "clean up" unused/old indices.     This should clean up the disk space and metadata around the indexes.

**Comment by prabhatsharma** [comment]
added in https://github.com/prabhatsharma/zinc/commit/b85c4c852953edfb417d833c43120f390489b255

**Comment by prabhatsharma** [comment]
@beave Can we close this issue?
