### ISSUE TITLE
Unable to search field with value containing dot "."

### ISSUE THREAD

**Issue by ayrbox** [prabhatsharma/zinc#61]
Hi @prabhatsharma

First thanks for creating Zinc. For now, its amazing for small applications and I am sure more features are coming.

I was playing with Zinc after reading your article. I tested with data with email addresses. There are no issues with writing/reading documents but on search it does not seems to consider email. I tried to encode email address and tried few ways and found that search does not work as soon as I add dot "." any data.

I tried to debug from source but my skill is limited with go lang so its not much help.

![Screenshot from 2021-12-30 22-15-00](https://user-images.githubusercontent.com/9810337/147791374-60cb1364-bad1-41bb-9b4f-b9da1e419c8b.png)

![Screenshot from 2021-12-30 22-16-06](https://user-images.githubusercontent.com/9810337/147791389-1cfa437b-40c8-4f66-960a-aa286b535551.png)

Thanks

**Comment by prabhatsharma** [comment]
querystring by default does "match" search which searches for the whole word. In order for you to be able to search for partial words you could use wildcard search. e.g.
>  *gmail.com -> This should search for all email with gmail.com domain

Let me know if this helps.

**Comment by ayrbox** [comment]
Thank you for the quick reply and **yes it does work as you suggested** :tada: 

Suggestion:
I don't how ES works and I am assuming Zinc is doing similar kind of search type that ES supports. May be its good to add how different `search_type` works. If you can direct me to resource when I can learn more about the `search_types` then I can help with adding to readme or may be just addd link to page about search_types (if already exists).

Thank you again :+1:

**Comment by prabhatsharma** [comment]
Am glad it worked for you. Zinc is a relatively very young project. First released on Dec 3rd 2021. I still have work to put in basic documentation. Will do it soon.
