### ISSUE TITLE
is there anyone met this problem with docker ?

### ISSUE THREAD

**Issue by ssuhvs** [prabhatsharma/zinc#64]
goroutine 1 [running]:
github.com/prabhatsharma/zinc/pkg/core.LoadZincSystemIndexes()
	/go/src/github.com/prabhatsharma/zinc/pkg/core/LoadIndexes.go:25 +0x137
github.com/prabhatsharma/zinc/pkg/core.init()
	/go/src/github.com/prabhatsharma/zinc/pkg/core/types.go:10 +0x3c
{"level":"debug","time":"2022-01-04T14:23:59Z","message":"Loading indexes..."}
{"level":"debug","time":"2022-01-04T14:23:59Z","message":"Loading system indexes..."}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x958bd7]

**Comment by ssuhvs** [comment]
what`s wrong ?

**Comment by prabhatsharma** [comment]
Check this https://github.com/prabhatsharma/zinc/issues/23#issuecomment-987641635. container is non privileged to make it secure. 

Let me know if it helps.

**Comment by prabhatsharma** [comment]
@ssuhvs Were you able to resolve it? Can we close the issue?
