### ISSUE TITLE
It seems doesn't support the use of "_source"

### ISSUE THREAD

**Issue by Dorbmon** [prabhatsharma/zinc#66]
When adding "_source" in query request, it still returns all the fields.

**Comment by prabhatsharma** [comment]
It's not implemented yet. Can you tell us more about your use case and what you are trying to do, so we make sure that it is catered to during development.

**Comment by tjkusnadi** [comment]
For me, the use case is when client request a search, we just return field needed on the client side
E.g all fields.
"userId", "email", "phoneNumber".

so for public search, we don't need to return userId for client,
but on admin side when searching for data, userId needed in response.

that way on elasticsearch, we just play with the _source filter.

**Comment by safeie** [comment]
this pr will be help #78

**Comment by prabhatsharma** [comment]
Is available in latest release. Closing issue.
