### ISSUE TITLE
armv6 Docker image

### ISSUE THREAD

**Issue by jkulcsar** [prabhatsharma/zinc#68]
Would it be possible to have an armv6 Docker image also? Thank you.

**Comment by prabhatsharma** [comment]
sure. I will build one and update here. Where are you planning to run it?

**Comment by jkulcsar** [comment]
On some older RPis, still on arm6.
Not sure a Docker image would make a difference; tried to run the arm6  binary directly, both ingestion and search are very slow, uses much more memory than x86_64.
