### ISSUE TITLE
No search results on the example from README

### ISSUE THREAD

**Issue by wsw70** [prabhatsharma/zinc#7]
After staring `zinc` on Windows 10, loading the data from the README python script, and choosing the `games3` index, no results are returned - despite choosing `1 day` (or longer) as the time scale (the test was done an hour or so ago).

There are no logs (except a successful authentication).

The data is in because the available labels are displayed in the left drawer.

![image](https://user-images.githubusercontent.com/1345886/144705853-75791d91-37c2-4447-aeb6-cc4bd5097521.png)

**Comment by prabhatsharma** [comment]
It does not show the documents by default yet. Search for something and it should appear.

**Comment by wsw70** [comment]
> It does not show the documents by default yet

OK I understand. I will be waiting for that feature then (it is useful to have a look at logs for instance)

**Comment by landmaj** [comment]
I had the same problem and thought something was wrong, now I just type `*` into search box to look at logs without searching for anything in particular.

**Comment by B0bbyD0llar** [comment]
> I had the same problem and thought something was wrong, now I just type `*` into search box to look at logs if I'm not looking for anything specific.

Hi, 
did you select an index before searching?
